# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9918bedac45f1449550d0836766a58bddad507af96e3a543298e4182f14d707c7a228d1e123b1a69cf94a35b090c73c127c929eb2e5a6abcbb431028ab807598

test:
  secret_key_base: 2aed7ab45d981e2b3ea6246482931678c9b232415ae3b11c7f9fb82bd90372a7d18c79f541ed38ee1fb0dd7f305e24785c168beb99e7fe3449fc850dffb40288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
